### ISSUE TITLE
Consumable output by for example xargs

### ISSUE THREAD

**Issue by slothyrulez** [thombashi/cleanpy#1]
Hi,

It will be nice if there is an option to just "log" the paths to delete, so they can be consumed by other unix tools, for exaple xargs.

Thanks for you effort and for the tool.

**Comment by thombashi** [comment]
@slothyrulez 
Thank you for your feedback.

I had added `--list` option at `cleanpy 0.2`.
You can just print paths to delete with this option.
Please try to upgrade the package.
